[package]
name = "aspect2-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.9"
log = "0.4.22"
simple_logger = "5.0.0"
anyhow = "1.0.100"
rand = "0.9.2"
libaspect2 = { path = "../" }

[[bin]]
name = "postcode_emu"

[[bin]]
name = "soundchip_cli"
