name: CI

on:
  push:
#    branches: [ main, master ]
  pull_request:
#    branches: [ main, master ]

jobs:
  test-crates:
    name: Build & Test crates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ "i2c", "emmc_spi" ]
        rust: [ "stable" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ matrix.crate }}/target
          key: ${{ runner.os }}-cargo-${{ matrix.crate }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: Build (release)
        run: cargo build --manifest-path ${{ matrix.crate }}/Cargo.toml --release --verbose

      - name: Run tests
        run: cargo test --manifest-path ${{ matrix.crate }}/Cargo.toml --verbose --all-features

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-release
          path: ${{ matrix.crate }}/target/release
